spring:
  kafka:
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
      properties:
        session.timeout.ms: 120000
        max.poll.interval.ms: 300000
        max.poll.records: 2